env: "local"

database:
  host: "db"
  port: 5432
  user: "warehouse-control-user"
  password: "your_password"
  dbname: "warehouse_control_db"
  sslmode: "disable"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s